<?php

declare(strict_types=1);

namespace Workflow\V2\Enums;

enum HistoryEventType: string
{
    case StartAccepted = 'StartAccepted';
    case StartRejected = 'StartRejected';
    case WorkflowStarted = 'WorkflowStarted';
    case WorkflowContinuedAsNew = 'WorkflowContinuedAsNew';
    case ChildWorkflowScheduled = 'ChildWorkflowScheduled';
    case ChildCancellationRequested = 'ChildCancellationRequested';
    case ChildCancellationResolved = 'ChildCancellationResolved';
    case ChildRunStarted = 'ChildRunStarted';
    case ChildRunCompleted = 'ChildRunCompleted';
    case ChildRunFailed = 'ChildRunFailed';
    case ChildRunCancelled = 'ChildRunCancelled';
    case ChildRunTerminated = 'ChildRunTerminated';
    case ServiceCallStarted = 'ServiceCallStarted';
    case ServiceCallCompleted = 'ServiceCallCompleted';
    case ServiceCallFailed = 'ServiceCallFailed';
    case ServiceCallCancelled = 'ServiceCallCancelled';
    case ConditionWaitOpened = 'ConditionWaitOpened';
    case ConditionWaitSatisfied = 'ConditionWaitSatisfied';
    case ConditionWaitTimedOut = 'ConditionWaitTimedOut';
    case ConditionWaitCancelled = 'ConditionWaitCancelled';
    case SignalWaitOpened = 'SignalWaitOpened';
    case SignalWaitCancelled = 'SignalWaitCancelled';
    case SignalReceived = 'SignalReceived';
    case SignalApplied = 'SignalApplied';
    case UpdateAccepted = 'UpdateAccepted';
    case UpdateRejected = 'UpdateRejected';
    case UpdateApplied = 'UpdateApplied';
    case UpdateCompleted = 'UpdateCompleted';
    case RepairRequested = 'RepairRequested';
    case CancelRequested = 'CancelRequested';
    case CooperativeCancellationRequested = 'CooperativeCancellationRequested';
    case CooperativeCancellationDelivered = 'CooperativeCancellationDelivered';
    case CancellationScopeOpened = 'CancellationScopeOpened';
    case CancellationScopeRequested = 'CancellationScopeRequested';
    case CancellationScopeDeliveryPrepared = 'CancellationScopeDeliveryPrepared';
    case CancellationScopeDelivered = 'CancellationScopeDelivered';
    case CancellationScopeRequestConflicted = 'CancellationScopeRequestConflicted';
    case WorkflowCancelled = 'WorkflowCancelled';
    case TerminateRequested = 'TerminateRequested';
    case WorkflowTerminated = 'WorkflowTerminated';
    case ArchiveRequested = 'ArchiveRequested';
    case WorkflowArchived = 'WorkflowArchived';
    case ActivityScheduled = 'ActivityScheduled';
    case ActivityStarted = 'ActivityStarted';
    case ActivityHeartbeatRecorded = 'ActivityHeartbeatRecorded';
    case ActivityRetryScheduled = 'ActivityRetryScheduled';
    case ActivityCompleted = 'ActivityCompleted';
    case ActivityFailed = 'ActivityFailed';
    case ActivityCancelled = 'ActivityCancelled';
    case ActivityCancellationAcknowledged = 'ActivityCancellationAcknowledged';
    case ActivityTimedOut = 'ActivityTimedOut';
    case FailureHandled = 'FailureHandled';
    case SideEffectRecorded = 'SideEffectRecorded';
    case VersionMarkerRecorded = 'VersionMarkerRecorded';
    case TimerScheduled = 'TimerScheduled';
    case TimerFired = 'TimerFired';
    case TimerCancelled = 'TimerCancelled';
    case SelectionResolved = 'SelectionResolved';
    case SelectionOperationCancelled = 'SelectionOperationCancelled';
    case SearchAttributesUpserted = 'SearchAttributesUpserted';
    case MemoUpserted = 'MemoUpserted';
    case WorkflowTimedOut = 'WorkflowTimedOut';
    case WorkflowCompleted = 'WorkflowCompleted';
    case WorkflowFailed = 'WorkflowFailed';
    case ParentClosePolicyApplied = 'ParentClosePolicyApplied';
    case ParentClosePolicyFailed = 'ParentClosePolicyFailed';
    case ParentCloseCancellationRequested = 'ParentCloseCancellationRequested';
    case MessageCursorAdvanced = 'MessageCursorAdvanced';
    case ScheduleCreated = 'ScheduleCreated';
    case SchedulePaused = 'SchedulePaused';
    case ScheduleResumed = 'ScheduleResumed';
    case ScheduleUpdated = 'ScheduleUpdated';
    case ScheduleTriggered = 'ScheduleTriggered';
    case ScheduleDeleted = 'ScheduleDeleted';
    case ScheduleTriggerSkipped = 'ScheduleTriggerSkipped';
}
