<?php

declare(strict_types=1);

namespace Tests\Feature\V2;

use Tests\Fixtures\V2\TestGreetingWorkflow;
use Tests\TestCase;
use Workflow\Serializers\Serializer;
use Workflow\V2\Contracts\WorkflowControlPlane;
use Workflow\V2\Enums\HistoryEventType;
use Workflow\V2\Enums\RunStatus;
use Workflow\V2\Enums\TaskStatus;
use Workflow\V2\Enums\TaskType;
use Workflow\V2\Models\WorkflowHistoryEvent;
use Workflow\V2\Models\WorkflowInstance;
use Workflow\V2\Models\WorkflowRun;
use Workflow\V2\Models\WorkflowTask;
use Workflow\V2\Support\DefaultWorkflowControlPlane;

final class V2WorkflowControlPlaneTest extends TestCase
{
    private WorkflowControlPlane $controlPlane;

    protected function setUp(): void
    {
        parent::setUp();

        config()->set('workflows.v2.compatibility.current', 'build-a');
        config()->set('workflows.v2.compatibility.supported', ['build-a']);

        $this->controlPlane = $this->app->make(WorkflowControlPlane::class);
    }

    public function testControlPlaneIsResolvableFromContainer(): void
    {
        $controlPlane = $this->app->make(WorkflowControlPlane::class);

        $this->assertInstanceOf(DefaultWorkflowControlPlane::class, $controlPlane);
    }

    public function testStartWithLocallyResolvableClass(): void
    {
        config()->set('workflows.v2.types.workflows', [
            'test-greeting-workflow' => TestGreetingWorkflow::class,
        ]);

        $result = $this->controlPlane->start('test-greeting-workflow', 'ctrl-plane-test-1', [
            'arguments' => Serializer::serialize(['Taylor']),
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $this->assertTrue($result['started']);
        $this->assertSame('ctrl-plane-test-1', $result['workflow_instance_id']);
        $this->assertNotNull($result['workflow_run_id']);
        $this->assertSame('test-greeting-workflow', $result['workflow_type']);
        $this->assertSame('started_new', $result['outcome']);
        $this->assertNotNull($result['task_id']);
        $this->assertNull($result['reason']);

        $instance = WorkflowInstance::query()->find('ctrl-plane-test-1');
        $this->assertNotNull($instance);
        $this->assertSame('test-greeting-workflow', $instance->workflow_type);

        $run = WorkflowRun::query()->find($result['workflow_run_id']);
        $this->assertNotNull($run);
        $this->assertSame(RunStatus::Pending, $run->status);

        $task = WorkflowTask::query()->find($result['task_id']);
        $this->assertNotNull($task);
        $this->assertSame(TaskStatus::Ready, $task->status);
        $this->assertSame(TaskType::Workflow, $task->task_type);

        $startedEvent = WorkflowHistoryEvent::query()
            ->where('workflow_run_id', $run->id)
            ->where('event_type', HistoryEventType::WorkflowStarted->value)
            ->first();
        $this->assertNotNull($startedEvent);
        $this->assertArrayHasKey('declared_signals', $startedEvent->payload);
    }

    public function testStartWithTypeKeyOnly(): void
    {
        $result = $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-test-2', [
            'arguments' => Serializer::serialize(['arg1']),
            'connection' => 'redis',
            'queue' => 'remote-workers',
        ]);

        $this->assertTrue($result['started']);
        $this->assertSame('ctrl-plane-test-2', $result['workflow_instance_id']);
        $this->assertNotNull($result['workflow_run_id']);
        $this->assertSame('remote-workflow-type', $result['workflow_type']);
        $this->assertSame('started_new', $result['outcome']);
        $this->assertNotNull($result['task_id']);

        $instance = WorkflowInstance::query()->find('ctrl-plane-test-2');
        $this->assertNotNull($instance);
        $this->assertSame('remote-workflow-type', $instance->workflow_type);

        $run = WorkflowRun::query()->find($result['workflow_run_id']);
        $this->assertNotNull($run);
        $this->assertSame('redis', $run->connection);
        $this->assertSame('remote-workers', $run->queue);
        $this->assertSame('remote-workflow-type', $run->workflow_type);
        $this->assertSame('remote-workflow-type', $run->workflow_class);

        $startedEvent = WorkflowHistoryEvent::query()
            ->where('workflow_run_id', $run->id)
            ->where('event_type', HistoryEventType::WorkflowStarted->value)
            ->first();
        $this->assertNotNull($startedEvent);
        $this->assertArrayNotHasKey('declared_signals', $startedEvent->payload);
    }

    public function testStartWithAutoGeneratedInstanceId(): void
    {
        $result = $this->controlPlane->start('remote-workflow-type', null, [
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $this->assertTrue($result['started']);
        $this->assertNotEmpty($result['workflow_instance_id']);
        $this->assertNotNull($result['workflow_run_id']);
    }

    public function testStartRejectsDuplicate(): void
    {
        $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-dup-1', [
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $result = $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-dup-1');

        $this->assertFalse($result['started']);
        $this->assertSame('ctrl-plane-dup-1', $result['workflow_instance_id']);
        $this->assertSame('rejected_duplicate', $result['outcome']);
        $this->assertSame('instance_already_started', $result['reason']);
    }

    public function testStartReturnExistingActive(): void
    {
        $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-existing-1', [
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $result = $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-existing-1', [
            'duplicate_start_policy' => 'return_existing_active',
        ]);

        $this->assertTrue($result['started']);
        $this->assertSame('ctrl-plane-existing-1', $result['workflow_instance_id']);
        $this->assertSame('returned_existing_active', $result['outcome']);
    }

    public function testCancelActiveWorkflow(): void
    {
        $start = $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-cancel-1', [
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $result = $this->controlPlane->cancel('ctrl-plane-cancel-1', [
            'reason' => 'Testing cancellation',
        ]);

        $this->assertTrue($result['accepted']);
        $this->assertSame('ctrl-plane-cancel-1', $result['workflow_instance_id']);
        $this->assertNotNull($result['workflow_command_id']);
        $this->assertNull($result['reason']);
    }

    public function testTerminateActiveWorkflow(): void
    {
        $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-term-1', [
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $result = $this->controlPlane->terminate('ctrl-plane-term-1', [
            'reason' => 'Testing termination',
        ]);

        $this->assertTrue($result['accepted']);
        $this->assertSame('ctrl-plane-term-1', $result['workflow_instance_id']);
        $this->assertNotNull($result['workflow_command_id']);
        $this->assertNull($result['reason']);
    }

    public function testCancelNonExistentInstance(): void
    {
        $result = $this->controlPlane->cancel('nonexistent-instance');

        $this->assertFalse($result['accepted']);
        $this->assertNotNull($result['reason']);
    }

    public function testTerminateAlreadyClosedWorkflow(): void
    {
        $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-closed-1', [
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $this->controlPlane->terminate('ctrl-plane-closed-1');

        $result = $this->controlPlane->terminate('ctrl-plane-closed-1');

        $this->assertFalse($result['accepted']);
        $this->assertNotNull($result['reason']);
    }

    public function testSignalWithDurableContract(): void
    {
        config()->set('workflows.v2.types.workflows', [
            'test-greeting-workflow' => TestGreetingWorkflow::class,
        ]);

        $this->controlPlane->start('test-greeting-workflow', 'ctrl-plane-signal-1', [
            'arguments' => Serializer::serialize(['Taylor']),
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $result = $this->controlPlane->signal('ctrl-plane-signal-1', 'nonexistent_signal');

        $this->assertFalse($result['accepted']);
        $this->assertNotNull($result['reason']);
    }

    public function testQueryNonExistentInstance(): void
    {
        $result = $this->controlPlane->query('nonexistent-instance', 'getStatus');

        $this->assertFalse($result['success']);
        $this->assertNotNull($result['reason']);
    }

    public function testUpdateNonExistentInstance(): void
    {
        $result = $this->controlPlane->update('nonexistent-instance', 'setName');

        $this->assertFalse($result['accepted']);
        $this->assertNotNull($result['reason']);
    }

    public function testStartWithExplicitRoutingOverridesClassDefaults(): void
    {
        config()->set('workflows.v2.types.workflows', [
            'test-greeting-workflow' => TestGreetingWorkflow::class,
        ]);

        $result = $this->controlPlane->start('test-greeting-workflow', 'ctrl-plane-routing-1', [
            'arguments' => Serializer::serialize(['Taylor']),
            'connection' => 'redis',
            'queue' => 'custom-queue',
        ]);

        $this->assertTrue($result['started']);

        $run = WorkflowRun::query()->find($result['workflow_run_id']);
        $this->assertSame('redis', $run->connection);
        $this->assertSame('custom-queue', $run->queue);
    }

    public function testStartRecordsBusinessKeyAndLabels(): void
    {
        $result = $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-meta-1', [
            'connection' => 'redis',
            'queue' => 'default',
            'business_key' => 'order-12345',
            'labels' => ['team' => 'payments', 'env' => 'staging'],
            'memo' => ['description' => 'Test workflow'],
        ]);

        $this->assertTrue($result['started']);

        $run = WorkflowRun::query()->find($result['workflow_run_id']);
        $this->assertSame('order-12345', $run->business_key);
        $this->assertSame(['team' => 'payments', 'env' => 'staging'], $run->visibility_labels);
        $this->assertSame(['description' => 'Test workflow'], $run->memo);
    }

    public function testStartResolvesDottedDurableTypeKey(): void
    {
        config()->set('workflows.v2.types.workflows', [
            'tests.external-greeting-workflow' => TestGreetingWorkflow::class,
        ]);

        $result = $this->controlPlane->start('tests.external-greeting-workflow', 'ctrl-plane-dotted-1', [
            'arguments' => Serializer::serialize(['Taylor']),
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $this->assertTrue($result['started']);
        $this->assertSame('ctrl-plane-dotted-1', $result['workflow_instance_id']);
        $this->assertSame('tests.external-greeting-workflow', $result['workflow_type']);
        $this->assertNotNull($result['task_id']);

        $run = WorkflowRun::query()->find($result['workflow_run_id']);
        $this->assertNotNull($run);
        $this->assertSame(TestGreetingWorkflow::class, $run->workflow_class);
        $this->assertSame('tests.external-greeting-workflow', $run->workflow_type);

        // Dotted type key resolves to the real class, so command contract is captured.
        $startedEvent = WorkflowHistoryEvent::query()
            ->where('workflow_run_id', $run->id)
            ->where('event_type', HistoryEventType::WorkflowStarted->value)
            ->first();
        $this->assertNotNull($startedEvent);
        $this->assertArrayHasKey('declared_signals', $startedEvent->payload);
    }

    public function testStartThenPollReturnsSameTickTask(): void
    {
        $startResult = $this->controlPlane->start('remote-workflow-type', 'ctrl-plane-poll-1', [
            'connection' => 'redis',
            'queue' => 'default',
        ]);

        $this->assertTrue($startResult['started']);
        $this->assertNotNull($startResult['task_id']);

        // Poll immediately in the same request tick — task must be visible.
        $bridge = $this->app->make(\Workflow\V2\Contracts\WorkflowTaskBridge::class);
        $polled = $bridge->poll('redis', 'default');

        $this->assertNotEmpty($polled, 'Same-tick workflow task must be visible to poll().');

        $polledTaskIds = array_column($polled, 'task_id');
        $this->assertContains($startResult['task_id'], $polledTaskIds);
    }
}
