<?php

declare(strict_types=1);

namespace Workflow\V2\Support;

use InvalidArgumentException;
use Workflow\V2\Enums\HistoryEventType;

final class HistoryEventPayloadContract
{
    /**
     * @var list<string>
     */
    private const SELECTION_GROUP_KEYS = [
        'parallel_group_mode',
        'selection_member_key',
        'selection_member_index',
        'selection_member_base_sequence',
        'selection_member_size',
        'selection_member_kind',
    ];

    /**
     * @var array<string, list<string>>
     */
    private const PAYLOAD_KEYS = [
        'CancellationScopeRequested' => [
            'schema', 'workflow_run_id', 'scope_id', 'parent_scope_id', 'request_id', 'cancellation',
        ],
        'CancellationScopeDeliveryPrepared' => [
            'schema', 'workflow_run_id', 'scope_id', 'request_id', 'cancellation',
            'sequence', 'call_kind', 'sequence_span', 'operation_sequence', 'operation_sequence_span',
            'authority_deadline_at', 'activity_members', 'timer_members', 'wait_members',
        ],
        'SignalWaitCancelled' => [
            'signal_name', 'signal_wait_id', 'sequence', 'timeout_seconds', 'timer_id', 'cancelled_at', 'cancellation_scope',
        ],
        'ConditionWaitCancelled' => [
            'condition_wait_id', 'condition_wait_occurrence_id', 'condition_key', 'condition_definition_fingerprint',
            'sequence', 'timeout_seconds', 'timer_id', 'cancelled_at', 'cancellation_scope',
        ],
        'CancellationScopeDelivered' => [
            'schema', 'workflow_run_id', 'scope_id', 'request_id', 'cancellation',
            'sequence', 'call_kind', 'sequence_span', 'operation_sequence', 'operation_sequence_span',
            'authority_deadline_at', 'preparation_history_event_id',
        ],
        'CancellationScopeRequestConflicted' => [
            'schema', 'workflow_run_id', 'scope_id', 'parent_scope_id', 'reason',
            'accepted_cancellation', 'incoming_cancellation',
        ],
        'CancellationScopeOpened' => [
            'schema',
            'workflow_run_id',
            'sequence',
            'scope_id',
            'parent_scope_id',
            'shield_parent',
        ],
        'StartAccepted' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'workflow_class',
            'workflow_type',
            'business_key',
            'visibility_labels',
            'memo',
            'search_attributes',
            'outcome',
            'rejection_reason',
        ],
        'StartRejected' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'workflow_class',
            'workflow_type',
            'business_key',
            'visibility_labels',
            'memo',
            'search_attributes',
            'outcome',
            'rejection_reason',
        ],
        'WorkflowStarted' => [
            'workflow_class',
            'workflow_type',
            'workflow_instance_id',
            'workflow_run_id',
            'workflow_command_id',
            'business_key',
            'visibility_labels',
            'memo',
            'search_attributes',
            'execution_timeout_seconds',
            'run_timeout_seconds',
            'execution_deadline_at',
            'run_deadline_at',
            'workflow_definition_fingerprint',
            'workflow_definition_fingerprint_source',
            'declared_queries',
            'declared_query_contracts',
            'declared_signals',
            'declared_signal_contracts',
            'declared_updates',
            'declared_update_contracts',
            'declared_entry_method',
            'declared_entry_mode',
            'declared_entry_declaring_class',
            'parent_workflow_instance_id',
            'parent_workflow_run_id',
            'parent_sequence',
            'workflow_link_id',
            'child_call_id',
            'retry_policy',
            'timeout_policy',
            'continued_from_run_id',
            'resume_step_sequence',
            'recovery_kind',
            'replayed_started_at',
            'retry_attempt',
            'retry_of_child_workflow_run_id',
        ],
        'WorkflowContinuedAsNew' => [
            'sequence',
            'continued_to_run_id',
            'continued_to_run_number',
            'workflow_link_id',
            'closed_reason',
        ],
        'ActivityScheduled' => [
            'activity_execution_id',
            'activity_class',
            'activity_type',
            'sequence',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'local_preparation',
            'local_group_admission',
            'activity',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ActivityStarted' => [
            'activity_execution_id',
            'activity_attempt_id',
            'worker_attempt_id',
            'activity_class',
            'activity_type',
            'sequence',
            'attempt_number',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'local_preparation',
            'lease_expires_at',
            'activity',
            'activity_attempt',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ActivityHeartbeatRecorded' => [
            'activity_execution_id',
            'activity_attempt_id',
            'worker_attempt_id',
            'activity_class',
            'activity_type',
            'sequence',
            'attempt_number',
            'heartbeat_at',
            'lease_expires_at',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'activity',
            'activity_attempt',
            'progress',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ActivityRetryScheduled' => [
            'local_outcome',
            'local_recovery',
            'activity_execution_id',
            'activity_attempt_id',
            'worker_attempt_id',
            'activity_class',
            'activity_type',
            'sequence',
            'retry_task_id',
            'retry_of_task_id',
            'retry_available_at',
            'retry_backoff_seconds',
            'retry_after_attempt_id',
            'retry_after_attempt',
            'retry_reason',
            'max_attempts',
            'retry_policy',
            'timeout_kind',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'exception_type',
            'exception_class',
            'message',
            'code',
            'exception',
            'activity',
            'activity_attempt',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ActivityCompleted' => [
            'local_outcome',
            'activity_execution_id',
            'activity_attempt_id',
            'worker_attempt_id',
            'activity_class',
            'activity_type',
            'sequence',
            'attempt_number',
            'result',
            'payload_codec',
            'reused_from_run_id',
            'reused_activity_execution_id',
            'reused_recorded_at',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'activity',
            'activity_attempt',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ActivityFailed' => [
            'local_outcome',
            'local_recovery',
            'activity_execution_id',
            'activity_attempt_id',
            'worker_attempt_id',
            'activity_class',
            'activity_type',
            'sequence',
            'attempt_number',
            'failure_id',
            'failure_category',
            'non_retryable',
            'exception_type',
            'exception_class',
            'message',
            'code',
            'exception',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'activity',
            'activity_attempt',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
            'structural_limit_kind',
            'structural_limit_value',
            'structural_limit_configured',
        ],
        'ActivityCancelled' => [
            'cancellation_scope',
            'workflow_command_id',
            'activity_execution_id',
            'activity_attempt_id',
            'worker_attempt_id',
            'activity_class',
            'activity_type',
            'sequence',
            'attempt_number',
            'cancelled_at',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'activity',
            'activity_attempt',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ActivityCancellationAcknowledged' => [
            'sequence',
            'activity_execution_id',
            'activity_attempt_id',
            'worker_attempt_id',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'task',
            'lease_owner',
            'cancellation_history_event_id',
            'request_id',
            'root_request_id',
            'cleanup_deadline_at',
            'callback_state',
            'evidence_source',
            'acknowledged_at',
            'received_after_deadline',
        ],
        'ActivityTimedOut' => [
            'local_outcome',
            'local_recovery',
            'activity_execution_id',
            'activity_attempt_id',
            'worker_attempt_id',
            'activity_class',
            'activity_type',
            'sequence',
            'attempt_number',
            'failure_id',
            'failure_category',
            'timeout_kind',
            'message',
            'exception_class',
            'schedule_deadline_at',
            'close_deadline_at',
            'schedule_to_close_deadline_at',
            'heartbeat_deadline_at',
            'execution_mode',
            'local_activity',
            'workflow_task_id',
            'activity',
            'activity_attempt',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'TimerScheduled' => [
            'timer_id',
            'sequence',
            'delay_seconds',
            'fire_at',
            'cancellation_scope_id',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
            'timer_kind',
            'condition_wait_id',
            'condition_wait_occurrence_id',
            'condition_key',
            'condition_definition_fingerprint',
            'signal_wait_id',
            'signal_name',
        ],
        'TimerFired' => [
            'timer_id',
            'sequence',
            'delay_seconds',
            'fire_at',
            'fired_at',
            'cancellation_scope_id',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
            'timer_kind',
            'condition_wait_id',
            'condition_wait_occurrence_id',
            'condition_key',
            'condition_definition_fingerprint',
            'signal_wait_id',
            'signal_name',
        ],
        'SelectionResolved' => [
            'selection_group_id',
            'selection_group_base_sequence',
            'selection_group_size',
            'member_key',
            'member_index',
            'member_base_sequence',
            'member_size',
            'operation_kind',
            'operation_identity',
            'outcome',
            'resolution_event_id',
            'resolution_event_type',
        ],
        'SelectionOperationCancelled' => [
            'selection_group_id',
            'member_key',
            'member_index',
            'member_base_sequence',
            'member_size',
            'operation_kind',
            'operation_identity',
            'cancelled_at',
        ],
        'TimerCancelled' => [
            'timer_id',
            'cancellation_scope',
            'sequence',
            'delay_seconds',
            'fire_at',
            'timer_kind',
            'condition_wait_id',
            'condition_wait_occurrence_id',
            'condition_key',
            'condition_definition_fingerprint',
            'signal_wait_id',
            'signal_name',
            'cancelled_at',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'SignalReceived' => [
            'workflow_command_id',
            'signal_id',
            'workflow_instance_id',
            'workflow_run_id',
            'signal_name',
            'signal_wait_id',
            'arguments',
            'payload_codec',
        ],
        'SignalApplied' => [
            'workflow_command_id',
            'signal_id',
            'signal_name',
            'signal_wait_id',
            'sequence',
            'value',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'SignalWaitOpened' => [
            'signal_name',
            'signal_wait_id',
            'sequence',
            'timeout_seconds',
            'cancellation_scope_id',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'UpdateAccepted' => [
            'workflow_command_id',
            'update_id',
            'workflow_instance_id',
            'workflow_run_id',
            'update_name',
            'arguments',
            'ordering_state',
            'queued_behind_command_id',
            'queued_behind_command_sequence',
            'queued_behind_command_type',
        ],
        'UpdateRejected' => [
            'workflow_command_id',
            'update_id',
            'workflow_instance_id',
            'workflow_run_id',
            'update_name',
            'arguments',
            'validation_errors',
        ],
        'UpdateApplied' => [
            'workflow_command_id',
            'update_id',
            'workflow_instance_id',
            'workflow_run_id',
            'update_name',
            'arguments',
            'sequence',
        ],
        'UpdateCompleted' => [
            'workflow_command_id',
            'update_id',
            'workflow_instance_id',
            'workflow_run_id',
            'update_name',
            'sequence',
            'result',
            'failure_id',
            'failure_category',
            'non_retryable',
            'exception_type',
            'exception_class',
            'message',
            'code',
            'exception',
            'terminal_reason',
        ],
        'ConditionWaitOpened' => [
            'condition_wait_id',
            'condition_wait_occurrence_id',
            'condition_key',
            'condition_definition_fingerprint',
            'sequence',
            'timeout_seconds',
            'cancellation_scope_id',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ConditionWaitSatisfied' => [
            'condition_wait_id',
            'condition_wait_occurrence_id',
            'condition_key',
            'condition_definition_fingerprint',
            'sequence',
            'timer_id',
            'timeout_seconds',
            'workflow_signal_id',
            'signal_name',
            'signal_wait_id',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ConditionWaitTimedOut' => [
            'condition_wait_id',
            'condition_wait_occurrence_id',
            'condition_key',
            'condition_definition_fingerprint',
            'sequence',
            'timer_id',
            'timeout_seconds',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'SideEffectRecorded' => ['sequence', 'result'],
        'VersionMarkerRecorded' => ['sequence', 'change_id', 'version', 'min_supported', 'max_supported'],
        'ChildWorkflowScheduled' => [
            'sequence',
            'workflow_link_id',
            'child_call_id',
            'child_workflow_instance_id',
            'child_workflow_run_id',
            'child_workflow_class',
            'child_workflow_type',
            'child_run_number',
            'parent_close_policy',
            'cancellation_policy',
            'cancellation_scope_id',
            'retry_policy',
            'timeout_policy',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ChildRunStarted' => [
            'sequence',
            'workflow_link_id',
            'child_call_id',
            'child_workflow_instance_id',
            'child_workflow_run_id',
            'child_workflow_class',
            'child_workflow_type',
            'child_run_number',
            'child_status',
            'parent_close_policy',
            'cancellation_policy',
            'cancellation_scope_id',
            'retry_policy',
            'timeout_policy',
            'execution_timeout_seconds',
            'run_timeout_seconds',
            'execution_deadline_at',
            'run_deadline_at',
            'retry_attempt',
            'retry_of_child_workflow_run_id',
            'retry_backoff_seconds',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ChildRunCompleted' => [
            'sequence',
            'workflow_link_id',
            'child_call_id',
            'child_workflow_instance_id',
            'child_workflow_run_id',
            'child_workflow_class',
            'child_workflow_type',
            'child_run_number',
            'child_status',
            'closed_reason',
            'closed_at',
            'output',
            'result',
            'payload_codec',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ChildRunFailed' => [
            'sequence',
            'workflow_link_id',
            'child_call_id',
            'child_workflow_instance_id',
            'child_workflow_run_id',
            'child_workflow_class',
            'child_workflow_type',
            'child_run_number',
            'child_status',
            'closed_reason',
            'closed_at',
            'failure_id',
            'failure_category',
            'exception_type',
            'exception_class',
            'message',
            'exception',
            'code',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ChildRunCancelled' => [
            'sequence',
            'workflow_link_id',
            'child_call_id',
            'child_workflow_instance_id',
            'child_workflow_run_id',
            'child_workflow_class',
            'child_workflow_type',
            'child_run_number',
            'child_status',
            'closed_reason',
            'closed_at',
            'failure_id',
            'failure_category',
            'exception_class',
            'message',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ChildRunTerminated' => [
            'sequence',
            'workflow_link_id',
            'child_call_id',
            'child_workflow_instance_id',
            'child_workflow_run_id',
            'child_workflow_class',
            'child_workflow_type',
            'child_run_number',
            'child_status',
            'closed_reason',
            'closed_at',
            'failure_id',
            'failure_category',
            'exception_class',
            'message',
            'parallel_group_id',
            'parallel_group_kind',
            'parallel_group_base_sequence',
            'parallel_group_size',
            'parallel_group_index',
            'parallel_group_path',
        ],
        'ServiceCallStarted' => [
            'sequence',
            'service_call_id',
            'workflow_instance_id',
            'workflow_run_id',
            'caller_workflow_instance_id',
            'caller_workflow_run_id',
            'caller_sdk_language',
            'endpoint_name',
            'service_name',
            'operation_name',
            'service_sdk_language',
            'request_payload',
            'response_payload',
            'payload_codec',
            'operation_mode',
            'wait_for',
            'status',
            'outcome',
            'resolved_binding_kind',
            'resolved_target_reference',
            'linked_workflow_instance_id',
            'linked_workflow_run_id',
            'linked_workflow_update_id',
            'service_call',
            'response_or_failure_surface',
        ],
        'ServiceCallCompleted' => [
            'sequence',
            'service_call_id',
            'workflow_instance_id',
            'workflow_run_id',
            'caller_workflow_instance_id',
            'caller_workflow_run_id',
            'caller_sdk_language',
            'endpoint_name',
            'service_name',
            'operation_name',
            'service_sdk_language',
            'request_payload',
            'response_payload',
            'payload_codec',
            'operation_mode',
            'wait_for',
            'status',
            'outcome',
            'resolved_binding_kind',
            'resolved_target_reference',
            'linked_workflow_instance_id',
            'linked_workflow_run_id',
            'linked_workflow_update_id',
            'service_call',
            'response_or_failure_surface',
        ],
        'ServiceCallFailed' => [
            'sequence',
            'service_call_id',
            'workflow_instance_id',
            'workflow_run_id',
            'caller_workflow_instance_id',
            'caller_workflow_run_id',
            'caller_sdk_language',
            'endpoint_name',
            'service_name',
            'operation_name',
            'service_sdk_language',
            'request_payload',
            'response_payload',
            'payload_codec',
            'operation_mode',
            'wait_for',
            'status',
            'outcome',
            'resolved_binding_kind',
            'resolved_target_reference',
            'linked_workflow_instance_id',
            'linked_workflow_run_id',
            'linked_workflow_update_id',
            'service_call',
            'response_or_failure_surface',
            'exception_type',
            'exception_class',
            'message',
            'code',
            'exception',
        ],
        'ServiceCallCancelled' => [
            'sequence',
            'service_call_id',
            'workflow_instance_id',
            'workflow_run_id',
            'caller_workflow_instance_id',
            'caller_workflow_run_id',
            'caller_sdk_language',
            'endpoint_name',
            'service_name',
            'operation_name',
            'service_sdk_language',
            'request_payload',
            'response_payload',
            'payload_codec',
            'operation_mode',
            'wait_for',
            'status',
            'outcome',
            'resolved_binding_kind',
            'resolved_target_reference',
            'linked_workflow_instance_id',
            'linked_workflow_run_id',
            'linked_workflow_update_id',
            'service_call',
            'response_or_failure_surface',
            'exception_type',
            'exception_class',
            'message',
            'code',
            'exception',
        ],
        'SearchAttributesUpserted' => ['sequence', 'attributes', 'attribute_types', 'merged'],
        'MemoUpserted' => ['sequence', 'entries', 'merged'],
        'RepairRequested' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'command_type',
            'outcome',
            'liveness_state',
            'wait_kind',
            'task_id',
            'task_type',
        ],
        'CancelRequested' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'command_type',
            'reason',
        ],
        'CooperativeCancellationRequested' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'command_type',
            'reason',
            'cleanup_deadline_at',
            'cancellation',
        ],
        'CooperativeCancellationDelivered' => [
            'workflow_command_id', 'workflow_run_id', 'sequence', 'call_kind',
            'sequence_span', 'operation_sequence', 'operation_sequence_span',
            'cancellation',
        ],
        'WorkflowCancelled' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'failure_id',
            'failure_category',
            'closed_reason',
            'exception_class',
            'message',
            'reason',
            'cancellation_cleanup',
        ],
        'TerminateRequested' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'command_type',
            'reason',
        ],
        'WorkflowTerminated' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'failure_id',
            'failure_category',
            'closed_reason',
            'exception_class',
            'message',
            'reason',
        ],
        'ArchiveRequested' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'command_type',
            'outcome',
            'reason',
        ],
        'WorkflowArchived' => [
            'workflow_command_id',
            'workflow_instance_id',
            'workflow_run_id',
            'archive_command_id',
            'reason',
        ],
        'WorkflowTimedOut' => [
            'failure_id',
            'timeout_kind',
            'failure_category',
            'message',
            'exception_class',
            'execution_deadline_at',
            'run_deadline_at',
        ],
        'WorkflowCompleted' => ['output', 'payload_codec'],
        'WorkflowFailed' => [
            'failure_id',
            'failed_step_sequence',
            'failed_step_kind',
            'source_kind',
            'source_id',
            'failure_category',
            'non_retryable',
            'exception_type',
            'exception_class',
            'message',
            'exception',
            'structural_limit_kind',
            'structural_limit_value',
            'structural_limit_configured',
        ],
        'FailureHandled' => [
            'failure_id',
            'sequence',
            'failure_category',
            'source_kind',
            'source_id',
            'propagation_kind',
            'exception_class',
            'exception_type',
            'message',
            'handled',
        ],
        'ChildCancellationRequested' => [
            'sequence', 'policy', 'parent_request_id', 'root_request_id', 'cleanup_deadline_at',
            'child_workflow_instance_id', 'child_workflow_run_id', 'child_request_id',
            'child_root_request_id', 'child_cleanup_deadline_at', 'request_outcome', 'rejection_reason',
        ],
        'ChildCancellationResolved' => [
            'sequence', 'policy', 'parent_request_id', 'root_request_id', 'cleanup_deadline_at',
            'child_workflow_instance_id', 'child_workflow_run_id', 'child_status',
            'child_request_id', 'child_root_request_id', 'child_cleanup_deadline_at',
            'child_terminal_history_event_id', 'child_terminal_event_type', 'reason',
        ],
        'ParentCloseCancellationRequested' => [
            'parent_terminal_history_event_id', 'parent_terminal_event_type', 'cancellation',
        ],
        'ParentClosePolicyApplied' => [
            'child_instance_id', 'child_run_id', 'policy', 'reason', 'request_id', 'cancellation',
        ],
        'ParentClosePolicyFailed' => [
            'child_instance_id', 'child_run_id', 'policy', 'reason', 'error', 'request_id', 'cancellation',
            'request_diagnostics',
        ],
        'MessageCursorAdvanced' => ['stream_key', 'previous_position', 'new_position'],
        'ScheduleCreated' => ['spec', 'action', 'overlap_policy', 'next_fire_at', 'command_context'],
        'SchedulePaused' => ['reason', 'paused_at', 'command_context'],
        'ScheduleResumed' => ['next_fire_at', 'command_context'],
        'ScheduleUpdated' => ['changed_fields', 'spec', 'action', 'overlap_policy', 'next_fire_at', 'command_context'],
        'ScheduleTriggered' => [
            'workflow_instance_id',
            'workflow_run_id',
            'schedule_id',
            'schedule_ulid',
            'cron_expression',
            'timezone',
            'overlap_policy',
            'outcome',
            'effective_overlap_policy',
            'trigger_number',
            'occurrence_time',
            'command_context',
        ],
        'ScheduleDeleted' => ['reason', 'deleted_at', 'command_context'],
        'ScheduleTriggerSkipped' => ['reason', 'skipped_trigger_count', 'last_skipped_at', 'command_context'],
    ];

    /**
     * @return array<string, list<string>>
     */
    public static function payloadKeys(): array
    {
        $keys = self::PAYLOAD_KEYS;

        foreach ($keys as &$eventKeys) {
            if (in_array('parallel_group_path', $eventKeys, true)) {
                $eventKeys = array_values(array_unique([...$eventKeys, ...self::SELECTION_GROUP_KEYS]));
            }
        }
        unset($eventKeys);

        return $keys;
    }

    /**
     * @param array<string, mixed> $payload
     */
    public static function assertKnownPayloadKeys(HistoryEventType $eventType, array $payload): void
    {
        $allowed = self::payloadKeys()[$eventType->value] ?? null;

        if ($allowed === null) {
            throw new InvalidArgumentException(sprintf(
                'History event type %s is missing a documented payload contract.',
                $eventType->value,
            ));
        }

        $unknown = array_values(array_diff(array_keys($payload), $allowed));

        if ($unknown !== []) {
            throw new InvalidArgumentException(sprintf(
                '%s history payload contains undocumented key(s): %s.',
                $eventType->value,
                implode(', ', $unknown),
            ));
        }
    }
}
